package edu.baylor.ecs.jparser.model;

public enum InstanceType {
    CLASSCOMPONENT,
    INTERFACECOMPONENT,
    ANNOTATIONCOMPONENT,
    METHODCOMPONENT,
    MODULECOMPONENT,
    DIRECTORYCOMPONENT,
    ANALYSISCOMPONENT,
    FIELDCOMPONENT,
    IMPORTCOMPONENT
}
